version: "3.9"
services:
  customPostgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER = api
      - POSTGRES_PASSWORD = password
      - POSTGRES_DB=CUSTOM
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://api:password@postgres:5432/CUSTOM?sslmode=disable
    depends_on:
      - customPostgres
    entrypoint: ["/app/wait-for.sh","customPostgres:5432", "--","/app/start.sh"]
    command: ["/app/main"]
