version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=user_api
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=CUSTOM
    command: >
      sh -c "
      docker-entrypoint.sh postgres &
      sleep 10 &&
      psql -U user_api -d CUSTOM -c \"CREATE TABLE IF NOT EXISTS custom (
        id VARCHAR PRIMARY KEY,
        custom VARCHAR,
        fullname VARCHAR,
        email VARCHAR
      );\" &&
      psql -U user_api -d CUSTOM -c \"INSERT INTO custom (id, custom, fullname, email) VALUES 
        ('1', 'custom1', 'Full Name 1', 'email1@example.com'),
        ('2', 'custom2', 'Full Name 2', 'email2@example.com'),
        ('3', 'custom3', 'Full Name 3', 'email3@example.com'),
        ('4', 'custom4', 'Full Name 4', 'email4@example.com'),
        ('5', 'custom5', 'Full Name 5', 'email5@example.com');\"
      "
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://user_api:user_password@postgres:5432/CUSTOM?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432", "--","/app/start.sh"]
    command: ["/app/main"]

