version: "3.9"
services:
  postgres:
      image: postgres:12-alpine
      environment:
        - POSTGRES_USER=user_api
        - POSTGRES_PASSWORD=user_password
        - POSTGRES_DB=CUSTOM
  api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - DB_SOURCE=postgresql://user_api:user_password@postgres:5432/CUSTOM?sslmode=disable
      depends_on:
        - postgres
      entrypoint: ["/app/wait-for.sh","postgres:5432", "--","/app/start.sh"]
      command: ["/app/main"]
