version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=CUSTOM
    networks:
      - custom_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://api:password@postgres:5432/CUSTOM?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432", "--","/app/start.sh"]
    command: ["/app/main"]
    networks:
      - custom_network

networks:
  custom_network:

